---
- name: Openstack installation with ansible - Main
  hosts: openstack
  become: yes
  become_method: sudo

  tasks:
    - name: Update repositories
      apt: update_cache=yes

- include: controller/main.yaml
