---
- name: Keystone installation
  hosts: openstack
  become: yes
  become_method: sudo

  tasks:
    - name: Check presence of Keystone Database
      mysql_db:
        name: keystone
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_root_password }}"
        state: present

    - name: Create User keystone on database
      mysql_user:
        name: "{{ keystone_user_name }}"
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_root_password }}"
        password: "{{ keystone_user_password }}"
        priv: "{{ keystone_user_name}}.*:ALL,GRANT"
        state: present

    - name: Prevent keystone to start automatically after installation
      command: "echo manual > /etc/init/keystone.override"

    - name: Install keystone
      apt: name=keystone state=present

    - name: Install Apache2
      apt: name=apache2 state=present

    - name: Install libapache2-mod-wsgi
      apt: name=libapache2-mod-wsgi state=present

    - name: Install memcached
      apt: name=memcached state=present

    - name: Install python-memcache
      apt: name=python-memcache state=present
