---
- name: Keystone installation
  hosts: openstack
  become: yes
  become_method: sudo

  tasks:
    - name: Check presence of Keystone Database
      mysql_db:
        name: keystone
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_root_password }}"
        state: present

    - name: Create User keystone on database
      mysql_user:
        name: "{{ keystone_user_name }}"
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_root_password }}"
        password: "{{ keystone_user_password }}"
        priv: "{{ keystone_user_name}}.*:ALL,GRANT"
        state: present

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
